#lang planet neil/sicp
(define (make-account balance passwd)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE--ACCOUNT"
                       m))))
  (lambda (pwd m)
    (if (eq? pwd passwd)
        (dispatch m)
        (lambda (x) "Incorrect password"))))

(define acc (make-account 100 'pass))
((acc 'pass 'withdraw) 40)
((acc 'passd 'withdraw) 40)
((acc 'pass 'deposit) 50)