#lang planet neil/sicp
(define (next) (random 100))
(define a (next))
(define b (next))
(define (rand m)
    (cond ((eq? m 'generate) (set! a b) (set! b (next)) a)
          ((eq? m 'reset) (lambda (x) (set! b x)))
          (else "error")))
(rand 'generate)
((rand 'reset) 40)
(rand 'generate)
(rand 'generate)
(rand 'generate)
((rand 'reset) 40)
(rand 'generate)