#lang planet neil/sicp
(define (make-account balance passwd)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (changepwd m) (set! passwd m))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          ((eq? m 'changepwd) changepwd)
          (else (error "Unknown request -- MAKE--ACCOUNT"
                       m))))
  (lambda (pwd m)
    (if (eq? pwd passwd)
        (dispatch m)
        (lambda (x) "Incorrect password"))))

(define acc (make-account 100 'pass))
(define (make-joint user pwd npwd)
  (begin ((user pwd 'changepwd) npwd) user))
(define bcc (make-joint acc 'pass 'p))
((bcc 'p 'withdraw) 20)
((acc 'pass 'withdraw) 20)