#lang planet neil/sicp
(define (double f)
  (lambda (x) (f (f x))))
(define (inc x) (+ 1 x))
;((double inc) 1)
;; (((double (double double)) inc) 5)
((double ((double (double double)) inc)) 0)
(((double (double (double double))) inc) 0)
(((double ((double double) double)) inc) 0)
(newline)
(((double (double double)) inc) 0)
((((double double) double) inc) 0)
(newline)
(((double double) inc) 0)
((double (double inc)) 0)
((double inc) 0)