#lang planet neil/sicp
(define (adjoin-set x set)
  (cond ((null? set) (cons x set))
        ((> x (car set)) (cons (car set) (adjoin-set x (cdr set))))
        ((< x (car set)) (cons x set))))
(define s1 nil)
(define s2 (adjoin-set 4 s1))
(display s2)
(define s3 (adjoin-set 9 s2))
(display s3)
(define s4 (adjoin-set 13 s3))
(display s4)
(define s5 (adjoin-set 2 s4))
(display s5)
(define s6 (adjoin-set 10 s5))
(display s6)